<?php
declare(strict_types=1);

namespace Test\CQApi;

use GuzzleHttp\Client;
use JavaReact\CQApi\CQBalance;
use Monolog\Logger;

/**
 * Class OrderTest
 * @package Test\CQApi
 * @internal
 * @covers \JavaReact\CQApi\Order
 */
class BalanceTest extends BaseTest
{
    /** @var CQBalance */
    protected $balance;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $logger = new Logger("stdout");
        $logger->pushHandler(new StdoutHandler());
        $this->balance = new CQBalance('appid', 'appkey', function () {
            return new Client([
                "base_uri" => \JavaReact\CQApi\Client::TEST_GATEWAY,
            ]);
        }, $logger);
        $this->isDebug = true;//输出结果
    }

    public function testBalanceGet()
    {
        $response = $this->balance->balanceGet();
        $this->dump($response);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('15020190001', $response->result("app_id"));
    }
}