<?php

declare(strict_types=1);

namespace Test\CQApi;

use GuzzleHttp\Client;
use JavaReact\CQApi\CQCoupon;
use Monolog\Logger;

/**
 * Class OrderTest
 * @package Test\CQApi
 * @internal
 * @covers \JavaReact\CQApi\CQCoupon
 */
class CouponTest extends BaseTest
{
    /** @var CQCoupon */
    protected $coupon;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $logger = new Logger("stdout");
        $logger->pushHandler(new StdoutHandler());
        $this->coupon  = new CQCoupon('appid', 'appkey', function () {
            return new Client([
                "base_uri" => \JavaReact\CQApi\Client::TEST_GATEWAY,
            ]);
        }, $logger);
        $this->isDebug = true;//输出结果
    }

    /**
     * 商户购买卡劵接口
     */
    public function testOrderPay()
    {
        $response = $this->coupon->orderPay(strval(time()), '11002002', 1, '13800138000');//购买爱奇艺会员
        $this->dump($response);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('15020190001', $response->result("app_id"));
    }

    /**
     * 商户卡券订单查询接口
     */
    public function testOrderQuery()
    {
        $response = $this->coupon->orderQuery('1578468736');
        $this->dump($response);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('15020190001', $response->result("app_id"));
    }

    /**
     * 查询卡券品牌接口
     */
    public function testTypeList()
    {
        $response = $this->coupon->typeList();
        $this->dump($response);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('15020190001', $response->result("app_id"));
    }

    /**
     * 查询卡券品牌产品接口
     */
    public function testTypeGoodsList()
    {
        $response = $this->coupon->typeGoodsList('15');//爱奇艺会员
        $this->dump($response);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('15020190001', $response->result("app_id"));
    }

    /**
     * 查询卡券产品库存接口
     */
    public function testGoodsStock()
    {
        $response = $this->coupon->goodsStock('11002002');//爱奇艺月卡
        $this->dump($response);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('15020190001', $response->result("app_id"));
    }

    /**
     * 商户查询卡券产品使用须知接口
     */
    public function testGoodsNotes()
    {
        $response = $this->coupon->goodsNotes('11002002');//爱奇艺月卡
        $this->dump($response);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('暂无', $response->result());
    }
}