<?php

declare(strict_types=1);

namespace Test\CQApi;


use GuzzleHttp\Client;
use Monolog\Logger;
use PHPUnit\Framework\TestCase;
use JavaReact\CQApi\Goods;

/**
 * Class GoodsTest
 * @package Test\CQApi
 * @internal
 * @covers \JavaReact\CQApi\Goods
 */
class GoodsTest extends TestCase
{
    /**
     * @var Goods
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $logger = new Logger("stdout");
        $logger->pushHandler(new StdoutHandler());
        $this->goods = new Goods(Contains::TEST_APP_KEY, Contains::TEST_SECRET, function() {
            return new Client([
                "base_uri" => Contains::TEST_GATEWAY,
            ]);
        }, $logger);
    }

    public function testFuluGoodsInfoGet() {
        $response = $this->goods->fuluGoodsInfoGet(contains::TEST_GOODS_PRODUCT_ID);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame(contains::TEST_GOODS_PRODUCT_NAME, $response->result("product_name"));
    }

    public function testFuluGoodsTemplateGet() {
        $response = $this->goods->fuluGoodsTemplateGet(contains::TEST_GOODS_TEMPLATE_ID);
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame(contains::TEST_GOODS_TEMPLATE_ID, $response->result("AddressId"));
    }
}