<?php

declare(strict_types=1);

namespace Test\CQApi;


use GuzzleHttp\Client;
use JavaReact\CQApi\CQOrder;
use Monolog\Logger;
use PHPUnit\Framework\TestCase;

/**
 * Class OrderTest
 * @package Test\CQApi
 * @internal
 * @covers \JavaReact\CQApi\Order
 */
class OrderTest extends TestCase
{
    /** @var CQOrder */
    protected $order;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $logger = new Logger("stdout");
        $logger->pushHandler(new StdoutHandler());
        $this->order = new CQOrder('666', 'mykey', function () {
            return new Client([
                "base_uri" => \JavaReact\CQApi\Client::TEST_GATEWAY,
            ]);
        }, $logger);
    }

    /**
     * 话费充值接口
     */
    public function testTelPay()
    {
        $response = $this->order->telPay();
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('666', $response->result("app_id"));
    }

    /**
     * 流量充值接口
     */
    public function testGprsPay()
    {
        $response = $this->order->gprsPay();
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('666', $response->result("app_id"));
    }

    /**
     * 加油卡充值接口
     */
    public function testOilPay()
    {
        $response = $this->order->oilPay();
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('666', $response->result("app_id"));
    }

    /**
     * 腾讯业务接口
     */
    public function testQqPay()
    {
        $response = $this->order->qqPay();
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('666', $response->result("app_id"));
    }

    /**
     * 视频充值接口
     */
    public function testVideoPay()
    {
        $response = $this->order->videoPay();
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('666', $response->result("app_id"));
    }

    /**
     * 直充订单查询
     */
    public function testOrderGet()
    {
        $response = $this->order->orderGet();
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame('666', $response->result("app_id"));
    }
}