<?php

namespace Test\CQApi;

use GuzzleHttp\Client;
use JavaReact\CQApi\CQOrder;
use Monolog\Logger;

class SignTest extends BaseTest
{
    /** @var CQOrder */
    protected $order;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $logger = new Logger("stdout");
        $logger->pushHandler(new StdoutHandler());
        $this->order   = new CQOrder('app_id', 'app_key', function () {
            return new Client([
                "base_uri" => \JavaReact\CQApi\Client::TEST_GATEWAY,
            ]);
        }, $logger);
        $this->isDebug = true;//输出结果
    }

    /**
     * 话费充值接口回调验证
     */
    public function testSign()
    {
        $response = $this->order->verifySign([
            'order_no'  => '1578471536',
            'sign'      => '9FA0E855DB258C1CBA8DFD7DC79A4C06',
            'state'     => 'SUCCESS',
            'app_id'    => '15020190001',
            'timestamp' => '1578471759938',
        ]);
        $this->assertSame(true, $response);
    }
}