<?php

declare(strict_types=1);

namespace Test\CQApi;


use GuzzleHttp\Client;
use Monolog\Logger;
use PHPUnit\Framework\TestCase;
use JavaReact\CQApi\User;

/**
 * Class UserTest
 * @package Test\CQApi
 * @internal
 * @covers \JavaReact\CQApi\User
 */
class UserTest extends TestCase
{
    /**
     * @var User
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $logger = new Logger("stdout");
        $logger->pushHandler(new StdoutHandler());
        $this->user = new User(Contains::TEST_APP_KEY, Contains::TEST_SECRET, function() {
            return new Client([
                "base_uri" => Contains::TEST_GATEWAY,
            ]);
        }, $logger);
    }

    public function testFuluUserInfoGet() {
        $response = $this->user->fuluUserInfoGet();
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame(true, $response->isSuccess());
        $this->assertSame(contains::TEST_MERCHANT_NAME, $response->result("name"));
    }
}